apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-deployment
  labels:
    app: pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
      containers:
      - name: pg
        image: postgres:12.4-alpine
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: "test"
          - name: POSTGRES_USER
            value: "test"
          - name: POSTGRES_PASSWORD
            value: "test"
          - name: PGDATA
            value: "/var/lib/postgresql/data/data"
        volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: topo